---
- hosts: localhost
  
  vars:
    ssh_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD0eTzvYXj4ddqxz49CJsUBYD4wjLfhj6Py/AHKVPLEtq7hB2AeY+OLkkyDoDTC+mBIPgbS6aB2rGrc2vGM7q2w4Nw3a/rcXS5IIncMWlrznLd0E0r84OGdwQbGWfAP3RUX5pxRoykCHeE9hHpjN3xF0IM/RPgXNz+H5Z1325SSYTEorQ9JI6E75eQk/r9/aWF2yoZeFwLc5FDG6AQylHGNiiNeqMrR11TvbPomXd3H7zXgdwem+Egz23BNLt8TldrugzYj1vlx1qBazpHTbf95xpZGaMWiBcmo+Uy2BiVft5gO7YAl0et4japJYS2eQE0N5T0pJoIlWDz5ns2phVZt esa@x1y3

  tasks:
  - name: "Enable passwordless sudo"
    lineinfile:
      path: /etc/sudoers
      regexp: '%sudo.*'
      line: '%sudo	ALL=(ALL:ALL) NOPASSWD: ALL'

  - file:
      path: /etc/systemd/system/getty@tty1.service.d
      state: directory

  - name: "Set multi-user.target as default target"
    file:
      path: /etc/systemd/system/default.target
      src: /lib/systemd/system/graphical.target
      state: link

  - name: "Enable autologin on console"
    file:
      path: /etc/systemd/system/getty@tty1.service.d/override.conf
      state: file
      content: |
        [Service]
        ExecStart=
        ExecStart=-/sbin/agetty --autologin jetson %I $TERM

  - name: "Add authorized keys"
    authorized_key:
      user: jetson
      state: present
      key: "{{ item }}"
    loop: "{{ ssh_keys }}"
